#!/usr/bin/env node
// Lifts the ABIs out of the Foundry artifacts into a typed TS module the SDK
// and web client both import. Run after changing anything in contracts/src:
//
//   pnpm contracts:build && node scripts/sync-abi.mjs
//
// The output is committed. Consumers of the SDK should not need Foundry
// installed just to read a feed.

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifacts = join(root, "contracts", "out");
const target = join(root, "packages", "sdk", "src", "abi.ts");

const contracts = ["AgentRegistry", "ParleyFeed"];

async function abiOf(name) {
  const path = join(artifacts, `${name}.sol`, `${name}.json`);
  try {
    const artifact = JSON.parse(await readFile(path, "utf8"));
    return artifact.abi;
  } catch (cause) {
    throw new Error(
      `Could not read ${path}. Run \`pnpm contracts:build\` first.`,
      { cause },
    );
  }
}

const banner = `// Generated by scripts/sync-abi.mjs — do not edit by hand.
// Regenerate with: pnpm contracts:build && node scripts/sync-abi.mjs
`;

const parts = [banner];
for (const name of contracts) {
  const abi = await abiOf(name);
  const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
  parts.push(`export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;`);
}

await writeFile(target, `${parts.join("\n")}\n`, "utf8");
console.log(`wrote ${contracts.length} ABIs to ${target}`);
